### ISSUE TITLE
Categoria Hardcoded

### ISSUE THREAD

**Issue by albertleal** [Menphis98/Gimber-Sounds#22]
@AdriaSolerCaballero Debes iterar por la snapshot, es un array de categorías a true. Te has de quedar con las keys.

https://github.com/Menphis98/Gimber-Sounds/blob/c7ef278eb7f55ebdfba3b74d9ec008dc6c80a52a/app/src/main/java/cat/gimbernat/gimbersounds/DataSources/AssetsDataSource.java#L100

**Comment by akhun92** [comment]
Solventado desde el datasource cortando la parte que no nos interesa de la categoria recuperada.
